name: Check PEP8 Compliance

on: [push]

jobs:
  check-pep8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip
    - run: |
        python -m pip install --upgrade pip
        pip install pycodestyle
    - run: pycodestyle --show-source $(git ls-files '*.py')
